/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DevlinImport } from './routes/devlin'
import { Route as AuroraImport } from './routes/aurora'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DevlinRoute = DevlinImport.update({
  id: '/devlin',
  path: '/devlin',
  getParentRoute: () => rootRoute,
} as any)

const AuroraRoute = AuroraImport.update({
  id: '/aurora',
  path: '/aurora',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/aurora': {
      id: '/aurora'
      path: '/aurora'
      fullPath: '/aurora'
      preLoaderRoute: typeof AuroraImport
      parentRoute: typeof rootRoute
    }
    '/devlin': {
      id: '/devlin'
      path: '/devlin'
      fullPath: '/devlin'
      preLoaderRoute: typeof DevlinImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aurora': typeof AuroraRoute
  '/devlin': typeof DevlinRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aurora': typeof AuroraRoute
  '/devlin': typeof DevlinRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/aurora': typeof AuroraRoute
  '/devlin': typeof DevlinRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aurora' | '/devlin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aurora' | '/devlin'
  id: '__root__' | '/' | '/aurora' | '/devlin'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuroraRoute: typeof AuroraRoute
  DevlinRoute: typeof DevlinRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuroraRoute: AuroraRoute,
  DevlinRoute: DevlinRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aurora",
        "/devlin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/aurora": {
      "filePath": "aurora.tsx"
    },
    "/devlin": {
      "filePath": "devlin.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
